In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline


# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [32]:
i = np.arange(1, 21)
vector = 2 ** i / i
print(vector)


[2.00000000e+00 2.00000000e+00 2.66666667e+00 4.00000000e+00
 6.40000000e+00 1.06666667e+01 1.82857143e+01 3.20000000e+01
 5.68888889e+01 1.02400000e+02 1.86181818e+02 3.41333333e+02
 6.30153846e+02 1.17028571e+03 2.18453333e+03 4.09600000e+03
 7.71011765e+03 1.45635556e+04 2.75941053e+04 5.24288000e+04]


**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
i = np.arange(0, 6)
vector = 0.1 ** (3 * i) * 0.2 ** (4 * i)
s = sum(vector)
print(s)


1.00000160000256


**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [26]:
matrix = np.ones((8, 8))
matrix[::2, 1::2] = 0
matrix[1::2, ::2] = 0
print(matrix)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [79]:
X = np.random.random((5, 2))

print(X)
Xp = np.ones((5, 2))
Xp[:, 0] = np.sqrt(np.sum(X ** 2, axis=1))
Xp[:, 1] = np.arctan(X[:, 1] / X[:, 0])
print(Xp)


[[0.97465782 0.65313459]
 [0.10815119 0.55981671]
 [0.79908019 0.29420212]
 [0.06133746 0.278114  ]
 [0.11321555 0.77047813]]
[[1.17326154 0.59038736]
 [0.57016789 1.37995699]
 [0.85151867 0.35277457]
 [0.28479761 1.35372349]
 [0.77875177 1.42489848]]


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [74]:
X = np.random.random((10, 10))

print(X)
arg = np.argmax(X)
print((arg // 10, arg % 10))


[[0.52207213 0.81751449 0.52357525 0.95813869 0.44479342 0.20891836
  0.40275238 0.23716089 0.15913875 0.02546548]
 [0.70759497 0.54767312 0.81601919 0.31051752 0.91779215 0.22900638
  0.67336968 0.19211136 0.98851162 0.66841835]
 [0.87564734 0.1060854  0.9317057  0.88280017 0.42375684 0.2897718
  0.97297173 0.49334898 0.27933982 0.83726267]
 [0.11491065 0.37593997 0.14979822 0.93002052 0.17871705 0.96134013
  0.19913367 0.28279656 0.75591302 0.06554983]
 [0.25329555 0.93621446 0.23806085 0.06210504 0.61659997 0.35998637
  0.4643628  0.60695417 0.91653364 0.5079199 ]
 [0.62530492 0.65123191 0.69869598 0.06209894 0.02638158 0.93491164
  0.42700403 0.86396507 0.36768561 0.8550259 ]
 [0.39303747 0.926531   0.65830219 0.55279812 0.1452993  0.52238879
  0.18198799 0.76728033 0.02572206 0.00564182]
 [0.87075722 0.51660406 0.02161138 0.43567075 0.20564676 0.17492726
  0.88659713 0.54751844 0.97763056 0.6658465 ]
 [0.22544608 0.2049853  0.39496633 0.99862372 0.0614247  0.47617794
  0.50082856 

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [87]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

print(X)
print(y)
q = np.sqrt(np.sum((X - y) ** 2, axis=1))
print(X[np.argmin(q)])


[[0.94807584 0.77350496]
 [0.26107249 0.17920362]
 [0.97456584 0.48813398]
 [0.56750688 0.54968799]
 [0.32179938 0.99279348]
 [0.63187243 0.80025505]
 [0.40977411 0.59082025]
 [0.57539437 0.4223686 ]
 [0.08797759 0.77714883]
 [0.89503711 0.27398489]]
[[0.56691419 0.73175681]]
[0.63187243 0.80025505]


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [100]:
def f(x):
    if x < 0:
        return x**2 + 2*x + 6
    elif x >= 2:
        return x**2 + 4*x - 4
    else:
        return x + 6


x = np.arange(-3, 4)

list(map(f, x))


[9, 6, 5, 6, 7, 8, 17]

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [101]:
X = np.random.random((10, 10))

# print(X)
Xm = X - np.mean(X, axis=1, keepdims=True)
print(Xm)
print(np.mean(Xm, axis=1))


[[ 0.19148454  0.34263451 -0.18599243  0.27386861  0.08065815 -0.26233629
  -0.15728997 -0.12863233 -0.05834286 -0.09605192]
 [-0.46047167  0.27288605 -0.37431752  0.46658978 -0.33081467 -0.10411626
  -0.44191908  0.40371975  0.29104864  0.27739499]
 [ 0.38281239 -0.43531186  0.11222806  0.35556734  0.41204715 -0.35107118
  -0.34572238  0.20899863 -0.01957383 -0.31997432]
 [ 0.05389837  0.23130093 -0.06855446  0.38416312  0.21556389  0.44706944
  -0.34710588 -0.43684253 -0.01575524 -0.46373765]
 [ 0.36127411  0.39665921 -0.45203573  0.14896963  0.20391969 -0.45149594
   0.24988552 -0.3786352  -0.49513413  0.41659285]
 [-0.29722745  0.4464415   0.4860069   0.07706037 -0.27009926 -0.16672062
  -0.01503783 -0.40006679  0.4241278  -0.28448462]
 [ 0.11442114 -0.46332199 -0.32910444  0.44179362  0.29491245  0.31401317
   0.20142656 -0.3899025  -0.14436551 -0.0398725 ]
 [ 0.46470851  0.3260066  -0.17812678  0.34181972 -0.31657236  0.00443453
  -0.34485478 -0.12929246 -0.36964779  0.2015248 ]


**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [106]:
X = np.random.normal(loc=5, scale=2., size=1000)

print(np.mean(X), np.var(X))


5.142238627798979 4.064704943891719


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [107]:
x = np.arange(5)
x_ = x.reshape(5, 1)
x = x + x_
x = x % 5
print(x)


[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [115]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 3, 0, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [133]:
def sample(x, c):
    assert len(x) > 0

    s = np.sum(x)
    val = s * np.random.random(c)
    res = np.argmin((np.cumsum(x) <= val.reshape(-1, 1)), axis=1)
    return res


print(sample([50, 3, 1, 7, 20], 5))


[0 0 3 0 4]
